### ISSUE TITLE
Step completion for "go to coordinates" sometimes doesn't persist across sessions

### ISSUE THREAD

**Issue by lukeknoot** [max-ri/Guidelime#117]
I'm finding that whenever I log back in, there are a bunch of old steps that I have to manually mark as completed to get back to where I was. I believe most of these steps were auto-completed based on visiting coordinates.

I'm still trying to figure out a reliable way to reproduce this, but the below is a rough procedure.

Steps to reproduce
- Complete a bunch of steps that requires visiting a pair of coordinates
- Log out
- Log back in

Expected result
- Steps are still completed

Current result
- Some steps are not completed and have to be marked off manually to get back to where you were on the last session

I'll update this again after more testing. Just wanted to post this in-case anyone else has some insight here as to why this might happen.

**Comment by joslynesser** [comment]
I'm seeing this as well when doing test runs of a guide in https://github.com/lukeknoot/classicwow-to-guidelime but I can't seem to reproduce it 100%.

**Comment by max-ri** [comment]
Hi Luke,
sorry for not giving you an answer, when this was recent. I had to leave this project be inactive for a while. I don't know if you are still interested at all, but here are a couple of points to clear things up:

1. Guidelime doesn't persist the state of any auto-completed steps. The idea is that the auto-completion will also work retroactively and therefore when logging back in everything which was auto-completed will immediately be auto-completed again. Only manually completed steps are persisted by the addon so that these are still completed after relogging.

2. Steps whose only purpose it is to enable you to complete another step (such as going somewhere) should use the [OC] tag (i.e. optional and completed with the next step). I assume that the problem you describe could be solved by making your script add [OC] where appropriate (if you haven't already done so in the meantime). [OC] also works over more than one step. 
Here is an example:
`Enter the cave at [G x,y][OC]`
`Take the first turn left[OC]`
`Walk until the end of the tunnel[OC]`
`Turn right and take the second turn left[OC]`
`Accept [QA...]`
Since the first four steps only are there in order to let you find the quest giver hidden in the cave, they all get marked as completed once the quest is accepted. When you log in at a later time and the quest is already in your log (or completed) these steps will again appear as completed.

Very interesting project btw.

Cheers

**Comment by max-ri** [comment]
Step completion will now persist across sessions
