### ISSUE TITLE
Quests with wrong faction requirement

### ISSUE THREAD

**Issue by Zarant** [max-ri/Guidelime#119]
Quests "The Captain's Chest" (8551) and "The Captain's Cutlass" (8553) are marked as horde only, they should be available for both factions.

Source:
https://classic.wowhead.com/quest=8551/the-captains-chest
https://classic.wowhead.com/quest=8553/the-captains-cutlass

**Comment by max-ri** [comment]
Hi Zarant,
in the addon's quests database it is assumed that quests 614/615 are the alliance versions.
In order to check what is correct, you could help me by first updating Guidelime to at least 1.039 and then type /lime quests on an alliance character you have completed one or both of these quests on. If there is a message please send it to me (here or via Discord).
Thank you!

**Comment by max-ri** [comment]
fixed
