### ISSUE TITLE
Error when targeting friendly units/players

### ISSUE THREAD

**Issue by Gemini1661** [max-ri/Guidelime#140]
Received the following in TBC using Flymodo's guide with Questie and the latest version of Guidelime: 
`2x [ADDON_ACTION_BLOCKED] AddOn 'Guidelime' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>`

Was preventing me from targeting friendly units/.players.  I rolled back to the release behind current and was able to target friendlies, but received some demo guide errors that I don't really care about and don't affect me at level 60+.

**Comment by max-ri** [comment]
Thank you for reporting this issue and also for giving such a detailed report. I am sorry to hear this was causing you problems.
Not that this would help you in any way but I can guarantee that Guide was in fact not calling a function "CompactRaidFrame1:ClearAllPoints". Anyway, I will investigate the cause of this.
I do not think that any change made in 2.018 is responsible. That rolling back did seem to solve your problem was probably just a coincidence. You should consider going back to the current version as in 2.018 a major bug was fixed which will cause you another problem when going on in Flymolo's guide.

**Comment by max-ri** [comment]
As I am not able to reproduce this bug on my end I would need some more information from you.
What other addons are you using? Will this bug occur when disabling all other addons besides Guidelime, Flymolo, and Questie?
Thank you.

**Comment by Gemini1661** [comment]
I updated as you suggested and was grouped last night without any issue.  I run a lot of addons and others have also been updated.  Seems to be working as intended at this time.  Sorry for the goose chase.
