### ISSUE TITLE
Guidelime

### ISSUE THREAD

**Issue by Sarah8634** [max-ri/Guidelime#142]
I was recommended a week or 2 ago to try this mod. For the most part it is wonderful, unfortunately, its missing some info. For example, on a couple of occasions, when it tells you to get a quest, it tells you you need to get a prequest to be able to do this one, or a quest to unlock the new quest. This for example meant, I had to use wowhead to search that quest, find out who and where to collect and than run from one end of zone to other to collect, than I do actually do that quest to unlock the requirement for the current quest. In another instance, the guide tells you to go to the Inn in Theramore Isle to Fiora to collect a quest, only that quest/giver is in Auberdine...so you have to fly there and back to collect and hand in. Today I ran into the all mighty of problems. Quest needs me to loot an item, unfortunately, this item is not there (possibly bugged) so I had to leave it, this caused a further 2 quests to need to be skipped. It than asks me to go to darn, but than (Idk why) it tells me Im skipping this quest...potential repocussion from other quest.
Im now asked to go someone and loot a book, no book to loot, unfortunately I need a prequest to do this, so again, I wowhead the quest and who/where to get it and its back at my hearth, so I fly there, and the npc not only doesn't give the quest but you can't even talk to them. So, this line of quests undoable...and I don't know if the changes are prexisting or if they are bugged. So, a whole of xp lost.
The biggest issue however is inability to make contact with the creator. I simply wanted to send a message via curseforge and the discord link is invalid and had to make account here to do this and don't even know if this is the right place. Love this mod but needs to be easier way to make contact.

**Comment by Starsoar** [comment]
What specific guide are you using? It appears to be an issue with the written guide and not the guidelime add on itself. Did you get your issue resolved or pick a different guide?

**Comment by max-ri** [comment]
Sorry for the late replay.
Issues like these should be addressed by the creator of the guide. You could try to report the exact quest you ran into a problem with to them. Especially when you are trying to get into a guide when you are not starting it from the beginning some issues with not always having the exact correct quests at all times. A good guide should help you with that, eg by listing all quests you should have at the beginning of each segment.
Some issues with incorrect pre- and follow-up-quests can also be due to a bug in data obtained from Questie. Always keeping your Questie up-to-date can also be helpful.
